### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by bebbi** [Doodle3D/ThreeJS-export-STL#1]
Thanks for the inspiration, that's a clean way of doing the binary export.
I didn't use the package as-is mainly because of the jspm dependency. Any chance you can make that optional?
Also, I'd suggest to add threejs as a peerDependency.

**Comment by casperlamboo** [comment]
> I didn't use the package as-is mainly because of the jspm dependency. Any chance you can make that optional?

Oops, you are absolutely right, that should be a dev dependency https://github.com/Doodle3D/ThreeJS-export-STL/commit/c9a74a46d44bb83adb4ed6e0e247d09b0bd1d3e8

> Also, I'd suggest to add threejs as a peerDependency.

I was hoping I could write this three.js extension without importing three.js. This way when using the library you wouldn't have to worry about having installed three.js multiple times.

So instead of doing this
```javascript
  if (geometry instanceof THREE.BufferGeometry) {
```
I would do this
```javascript
  if (geometry.type === 'BufferGeometry') {
```
but in line https://github.com/Doodle3D/ThreeJS-export-STL/blob/master/src/index.js#L69 I have to use `THREE.Geometry`. I've added three.js as a jspm dependency. https://github.com/Doodle3D/ThreeJS-export-STL/commit/c39e02207ce1a576625a20b7ceb7b788d497f788

Not yet as a npm dependency. I'm using the modular source of three.js so I can write
```javascript
import { Geometry } from 'three/core/Geometry';
```
note sure yet how to set this up in npm

**Comment by bebbi** [comment]
You have a threejs dependency there. Just add threejs to `peerDependencies` and optionally `devDependencies`. It won't create duplicates as a lib. Make sure to specify a broad enough semver range for threejs in peerDependencies.

**Comment by casperlamboo** [comment]
I'm not quite sure if that would work, would you consider making a pull request showing the changes you are proposing?

**Comment by jafetmorales** [comment]
It's taking so long to install because of that dependency.

**Comment by casperlamboo** [comment]
added in https://github.com/Doodle3D/ThreeJS-export-STL/commit/0854117a45032bb174d806ae144fe7b58b9eadf3
